In [45]:
import numpy as np
import pandas as pd
from montecarlo import Die, Game, Analyzer

##### Die Class

In [7]:
dieA = Die(np.array([1,2,3,4,5,6]))
dieA.faces

array([1, 2, 3, 4, 5, 6])

In [8]:
dieA.weights

array([1., 1., 1., 1., 1., 1.])

In [10]:
dieA.chng_wght(4,3)
dieA.weights

array([1., 1., 1., 3., 1., 1.])

In [12]:
dieA.roll_die(10)
dieA.dataframe()

weights
faces         
1          1.0
2          1.0
3          1.0
4          3.0
5          1.0
6          1.0

##### Game Class

In [13]:
# SETUP for class 'Game'
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB]

In [14]:
game = Game(dice)
game.dice   # should return list of 'Die' objects

In [15]:
game.play(4)
game.play_results()

die1  die2
roll #            
1          1     2
2          4     2
3          3     5
4          1     4

In [18]:
game.play_results(form='narrow')

roll #      
1       die1    1
        die2    2
2       die1    4
        die2    2
3       die1    3
        die2    5
4       die1    1
        die2    4
dtype: int64


##### Analyzer Class

In [39]:
# set up for CLASS ANALYZE
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))
dieC = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB, dieC]

game = Game(dice)
game.play(3)
gameplay_df = game.play_results()
gameplay_narrow = game.play_results(form='narrow')

In [40]:
analyzed = Analyzer(game)
analyzed.jackpot()

'1 Jackpot!'

In [41]:
analyzed.face_count()

/Users/rickykuehn/Desktop/UVA/Summer/Programming/DS5100-finalproject-fmt2tg/montecarlo/montecarlo.py:195: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts_df = pd.DataFrame(columns=self.faces_array, index=self.play_results.index).fillna(0)


faces_counts  1  2  3  4  5  6
roll #                        
1             0  1  0  1  1  0
2             0  1  1  1  0  0
3             0  0  1  1  0  1

In [42]:
analyzed.combo_count()

die1  die2  die3
2     3     4       1
      4     5       1
3     4     6       1
Name: count, dtype: int64

In [43]:
analyzed.perm_count()

die1  die2  die3
2     4     3       1
            5       1
3     4     6       1
Name: count, dtype: int64