In [1]:
import pandas as pd
import numpy as np
from montecarlo import Die, Game, Analyzer

Welcome to Monte Carlo!


##### Die Class

In [2]:
dieA = Die(np.array([1,2,3,4,5,6]))
dieA.faces

array([1, 2, 3, 4, 5, 6])

In [3]:
dieA.weights

array([1., 1., 1., 1., 1., 1.])

In [4]:
dieA.chng_wght(4,3)
dieA.weights

array([1., 1., 1., 3., 1., 1.])

In [5]:
dieA.roll_die(10)

[6, 4, 4, 2, 4, 1, 6, 3, 5, 3]

In [6]:
dieA.dataframe()

weights
faces         
1          1.0
2          1.0
3          1.0
4          3.0
5          1.0
6          1.0

##### Game Class

In [7]:
# SETUP for class 'Game'
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB]

In [8]:
game = Game(dice)
game.dice   # should return list of 'Die' objects

In [9]:
game.play(4)
game.play_results()

die1  die2
roll #            
1          2     1
2          3     3
3          1     5
4          3     4

In [10]:
game.play_results(form='narrow')

die value
roll #                
1      die1          2
       die2          1
2      die1          3
       die2          3
3      die1          1
       die2          5
4      die1          3
       die2          4

##### Analyzer Class

In [11]:
# set up for CLASS ANALYZE
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))
dieC = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB, dieC]

game = Game(dice)
game.play(3)

In [12]:
analyzed = Analyzer(game)
analyzed.jackpot()

'1 Jackpot!'

In [13]:
analyzed.face_count()

faces_counts  1  2  3  4  5  6
roll #                        
1             0  1  1  1  0  0
2             0  0  0  3  0  0
3             0  0  1  2  0  0

In [14]:
analyzed.combo_count()

combo_counts
die1 die2 die3              
2    3    4                1
3    4    4                1
4    4    4                1

In [15]:
analyzed.perm_count()

perm_counts
die1 die2 die3             
3    4    2               1
          4               1
4    4    4               1