In [1]:
import pandas as pd
import numpy as np
from montecarlo import Die, Game, Analyzer

I've imported pandas, numpy, and the montecarlo module!


##### Die Class

In [2]:
dieA = Die(np.array([1,2,3,4,5,6]))
dieA.faces

array([1, 2, 3, 4, 5, 6])

In [3]:
dieA.weights

array([1., 1., 1., 1., 1., 1.])

In [4]:
dieA.chng_wght(4,3)
dieA.weights

array([1., 1., 1., 3., 1., 1.])

In [5]:
dieA.roll_die(10)

[5, 5, 4, 5, 3, 3, 4, 2, 6, 3]

In [6]:
dieA.dataframe()

weights
faces         
1          1.0
2          1.0
3          1.0
4          3.0
5          1.0
6          1.0

##### Game Class

In [7]:
# SETUP for class 'Game'
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB]

In [8]:
game = Game(dice)
game.dice   # should return list of 'Die' objects

In [9]:
game.play(4)
game.play_results()

die1  die2
roll #            
1          3     4
2          3     4
3          1     4
4          5     5

In [10]:
game.play_results(form='narrow')

die value
roll #                
1      die1          3
       die2          4
2      die1          3
       die2          4
3      die1          1
       die2          4
4      die1          5
       die2          5

##### Analyzer Class

In [11]:
# set up for CLASS ANALYZE
dieA = Die(np.array([1,2,3,4,5,6]))
dieB = Die(np.array([1,2,3,4,5,6]))
dieC = Die(np.array([1,2,3,4,5,6]))

dieA.chng_wght(3,4)
dieB.chng_wght(4,3)

dice=[dieA, dieB, dieC]

game = Game(dice)
game.play(3)
gameplay_df = game.play_results()
gameplay_narrow = game.play_results(form='narrow')

In [12]:
analyzed = Analyzer(game)
analyzed.jackpot()

'0 Jackpots :('

In [13]:
analyzed.face_count()

/Users/rickykuehn/Desktop/UVA/Summer/Programming/DS5100-finalproject-fmt2tg/montecarlo/montecarlo.py:173: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  counts_df = pd.DataFrame(columns=self.faces_array, index=self.play_results.index).fillna(0)


faces_counts  1  2  3  4  5  6
roll #                        
1             1  1  0  0  1  0
2             0  1  1  1  0  0
3             1  0  1  0  1  0

In [14]:
analyzed.combo_count()

combo_counts
die1 die2 die3              
1    2    5                1
     3    5                1
2    3    4                1

In [15]:
analyzed.perm_count()

perm_counts
die1 die2 die3             
1    5    3               1
3    2    4               1
5    2    1               1